-- A tenant can report a payment, but only the contract owner can make it paid.
-- Browser roles never write this table: the authenticated API calls the two
-- service-role-only functions below after verifying the caller's profile.

BEGIN;

CREATE TABLE public."Solicitud_pago" (
  id_solicitud_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pago bigint NOT NULL REFERENCES public."Pago"(id_pago) ON DELETE RESTRICT,
  id_contrato bigint NOT NULL REFERENCES public."Contrato"(id_contrato) ON DELETE RESTRICT,
  id_perfil_inquilino bigint NOT NULL REFERENCES public."Perfil"(id_perfil) ON DELETE RESTRICT,
  id_perfil_propietario bigint NOT NULL REFERENCES public."Perfil"(id_perfil) ON DELETE RESTRICT,
  estado text NOT NULL DEFAULT 'pendiente_revision'
    CHECK (estado IN ('pendiente_revision', 'aceptada', 'rechazada')),
  metodo_pago text NOT NULL CHECK (char_length(btrim(metodo_pago)) BETWEEN 1 AND 80),
  monto_informado numeric(14, 2) NOT NULL CHECK (monto_informado >= 0),
  solicitado_en timestamptz NOT NULL DEFAULT now(),
  resuelto_en timestamptz,
  id_perfil_resolutor bigint REFERENCES public."Perfil"(id_perfil) ON DELETE RESTRICT,
  motivo_rechazo text,
  CONSTRAINT solicitud_pago_resolution_consistency CHECK (
    (estado = 'pendiente_revision'
      AND resuelto_en IS NULL
      AND id_perfil_resolutor IS NULL
      AND motivo_rechazo IS NULL)
    OR (estado = 'aceptada'
      AND resuelto_en IS NOT NULL
      AND id_perfil_resolutor IS NOT NULL
      AND motivo_rechazo IS NULL)
    OR (estado = 'rechazada'
      AND resuelto_en IS NOT NULL
      AND id_perfil_resolutor IS NOT NULL
      AND char_length(btrim(coalesce(motivo_rechazo, ''))) BETWEEN 1 AND 500)
  )
);

CREATE INDEX solicitud_pago_contrato_solicitado_idx
  ON public."Solicitud_pago" (id_contrato, solicitado_en DESC);
CREATE INDEX solicitud_pago_inquilino_solicitado_idx
  ON public."Solicitud_pago" (id_perfil_inquilino, solicitado_en DESC);
CREATE INDEX solicitud_pago_propietario_solicitado_idx
  ON public."Solicitud_pago" (id_perfil_propietario, solicitado_en DESC);
CREATE INDEX solicitud_pago_pago_solicitado_idx
  ON public."Solicitud_pago" (id_pago, solicitado_en DESC);
CREATE UNIQUE INDEX solicitud_pago_unica_revision_pendiente_idx
  ON public."Solicitud_pago" (id_pago)
  WHERE estado = 'pendiente_revision';

ALTER TABLE public."Solicitud_pago" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."Solicitud_pago" FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public."Solicitud_pago" TO service_role;

-- The client only consumes notifications through its existing RLS-protected
-- query. Publishing INSERT events lets the bell refresh immediately; the
-- handler deliberately re-reads the row instead of trusting Realtime data.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1
      FROM pg_publication_tables
     WHERE pubname = 'supabase_realtime'
       AND schemaname = 'public'
       AND tablename = 'Notificacion'
  ) THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public."Notificacion";
    EXCEPTION WHEN insufficient_privilege THEN
      -- The workflow remains durable and the UI refreshes on focus. Do not
      -- make a data/security migration fail solely because this environment
      -- delegates Realtime-publication ownership to another role.
      RAISE NOTICE 'Notificacion was not added to supabase_realtime: insufficient privilege.';
    END;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.solicitar_revision_pago(
  p_pago_id bigint,
  p_id_perfil_inquilino bigint,
  p_metodo_pago text
)
RETURNS TABLE (
  id_solicitud_pago bigint,
  estado text,
  solicitado_en timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  payment_row public."Pago"%ROWTYPE;
  contract_row public."Contrato"%ROWTYPE;
  active_request public."Solicitud_pago"%ROWTYPE;
  normalized_method text := lower(btrim(coalesce(p_metodo_pago, '')));
BEGIN
  IF p_pago_id IS NULL
     OR p_id_perfil_inquilino IS NULL
     OR normalized_method NOT IN ('transferencia', 'mercado_pago', 'efectivo') THEN
    RAISE EXCEPTION 'Datos de pago inválidos.' USING ERRCODE = 'P0001';
  END IF;

  -- Serialize reports for one payment. This keeps the partial unique index
  -- from becoming a race condition while the transaction stays very short.
  SELECT *
    INTO payment_row
    FROM public."Pago"
   WHERE id_pago = p_pago_id
   FOR UPDATE;

  IF payment_row.id_pago IS NULL THEN
    RAISE EXCEPTION 'No se encontró el pago indicado.' USING ERRCODE = 'P0001';
  END IF;

  IF payment_row.fecha_pago IS NOT NULL THEN
    RAISE EXCEPTION 'Este pago ya fue confirmado.' USING ERRCODE = 'P0001';
  END IF;

  SELECT *
    INTO contract_row
    FROM public."Contrato"
   WHERE id_contrato = payment_row.id_contrato;

  IF contract_row.id_contrato IS NULL
     OR contract_row.id_perfil_inquilino <> p_id_perfil_inquilino THEN
    RAISE EXCEPTION 'El inquilino no puede informar este pago.' USING ERRCODE = '42501';
  END IF;

  SELECT *
    INTO active_request
    FROM public."Solicitud_pago" AS payment_request
   WHERE payment_request.id_pago = payment_row.id_pago
     AND payment_request.estado = 'pendiente_revision'
   ORDER BY payment_request.solicitado_en DESC, payment_request.id_solicitud_pago DESC
   LIMIT 1
   FOR UPDATE;

  -- Repeating the same action is idempotent and must not notify twice.
  IF active_request.id_solicitud_pago IS NOT NULL THEN
    RETURN QUERY
      SELECT active_request.id_solicitud_pago, active_request.estado, active_request.solicitado_en;
    RETURN;
  END IF;

  INSERT INTO public."Solicitud_pago" (
    id_pago,
    id_contrato,
    id_perfil_inquilino,
    id_perfil_propietario,
    estado,
    metodo_pago,
    monto_informado
  ) VALUES (
    payment_row.id_pago,
    contract_row.id_contrato,
    contract_row.id_perfil_inquilino,
    contract_row.id_perfil_propietario,
    'pendiente_revision',
    normalized_method,
    coalesce(payment_row.monto, 0)
      + CASE
          WHEN payment_row.interes_perdonado IS TRUE THEN 0
          ELSE coalesce(payment_row.monto_punitorio, 0)
        END
  )
  RETURNING * INTO active_request;

  INSERT INTO public."Notificacion" (
    titulo,
    mensaje,
    tipo,
    icono,
    enlace,
    rol_destino,
    rol_emisor,
    id_perfil_destino,
    id_perfil_emisor,
    leida
  ) VALUES (
    'Pago informado para revisar',
    format('El inquilino informó el pago correspondiente a %s. Revisalo desde Alquiler activo.', coalesce(payment_row.periodo, 'el período actual')),
    'pago_informado',
    'payments',
    'administrador.html#alquiler-activo',
    'OWNER',
    'TENANT',
    contract_row.id_perfil_propietario,
    contract_row.id_perfil_inquilino,
    false
  );

  RETURN QUERY
    SELECT active_request.id_solicitud_pago, active_request.estado, active_request.solicitado_en;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolver_revision_pago(
  p_id_solicitud_pago bigint,
  p_id_perfil_propietario bigint,
  p_aceptar boolean,
  p_motivo_rechazo text DEFAULT NULL
)
RETURNS TABLE (
  id_solicitud_pago bigint,
  estado text,
  resuelto_en timestamptz,
  id_pago bigint,
  fecha_pago date
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  request_row public."Solicitud_pago"%ROWTYPE;
  payment_row public."Pago"%ROWTYPE;
  contract_row public."Contrato"%ROWTYPE;
  request_payment_id bigint;
  normalized_reason text := nullif(btrim(coalesce(p_motivo_rechazo, '')), '');
  resolved_at timestamptz := now();
BEGIN
  IF p_id_solicitud_pago IS NULL OR p_id_perfil_propietario IS NULL OR p_aceptar IS NULL THEN
    RAISE EXCEPTION 'Datos de resolución inválidos.' USING ERRCODE = 'P0001';
  END IF;

  IF NOT p_aceptar AND (normalized_reason IS NULL OR char_length(normalized_reason) > 500) THEN
    RAISE EXCEPTION 'Indicá un motivo de rechazo de hasta 500 caracteres.' USING ERRCODE = 'P0001';
  END IF;

  -- Read the payment id first, then lock payment and request in this same
  -- order as solicitar_revision_pago to avoid deadlocks.
  SELECT payment_request.id_pago
    INTO request_payment_id
    FROM public."Solicitud_pago" AS payment_request
   WHERE payment_request.id_solicitud_pago = p_id_solicitud_pago;

  IF request_payment_id IS NULL THEN
    RAISE EXCEPTION 'No se encontró la solicitud de pago.' USING ERRCODE = 'P0001';
  END IF;

  SELECT *
    INTO payment_row
    FROM public."Pago" AS payment
   WHERE payment.id_pago = request_payment_id
   FOR UPDATE;

  SELECT *
    INTO request_row
    FROM public."Solicitud_pago" AS payment_request
   WHERE payment_request.id_solicitud_pago = p_id_solicitud_pago
   FOR UPDATE;

  IF request_row.estado <> 'pendiente_revision' THEN
    RAISE EXCEPTION 'Esta solicitud ya fue resuelta.' USING ERRCODE = 'P0001';
  END IF;

  SELECT *
    INTO contract_row
    FROM public."Contrato"
   WHERE id_contrato = payment_row.id_contrato;

  IF contract_row.id_contrato IS NULL
     OR contract_row.id_perfil_propietario <> p_id_perfil_propietario
     OR request_row.id_perfil_propietario <> p_id_perfil_propietario THEN
    RAISE EXCEPTION 'El propietario no puede resolver esta solicitud.' USING ERRCODE = '42501';
  END IF;

  IF p_aceptar THEN
    IF payment_row.fecha_pago IS NOT NULL THEN
      RAISE EXCEPTION 'Este pago ya fue confirmado.' USING ERRCODE = 'P0001';
    END IF;

    UPDATE public."Solicitud_pago" AS payment_request
       SET estado = 'aceptada',
           resuelto_en = resolved_at,
           id_perfil_resolutor = p_id_perfil_propietario,
           motivo_rechazo = NULL
     WHERE payment_request.id_solicitud_pago = request_row.id_solicitud_pago
     RETURNING * INTO request_row;

    UPDATE public."Pago" AS payment
       SET fecha_pago = resolved_at
     WHERE payment.id_pago = payment_row.id_pago
     RETURNING * INTO payment_row;

    UPDATE public."Historial_pago" AS payment_history
       SET fecha_fin = resolved_at
     WHERE payment_history.id_pago = payment_row.id_pago
       AND payment_history.fecha_fin IS NULL;

    INSERT INTO public."Historial_pago" (
      id_pago,
      id_estado_pago,
      fecha_inicio
    ) VALUES (
      payment_row.id_pago,
      2,
      resolved_at
    );

    INSERT INTO public."Notificacion" (
      titulo,
      mensaje,
      tipo,
      icono,
      enlace,
      rol_destino,
      rol_emisor,
      id_perfil_destino,
      id_perfil_emisor,
      leida
    ) VALUES (
      'Pago confirmado',
      format('El propietario confirmó el pago correspondiente a %s.', coalesce(payment_row.periodo, 'el período actual')),
      'pago_aceptado',
      'task_alt',
      'tu-alquiler.html#alquiler',
      'TENANT',
      'OWNER',
      contract_row.id_perfil_inquilino,
      contract_row.id_perfil_propietario,
      false
    );
  ELSE
    UPDATE public."Solicitud_pago" AS payment_request
       SET estado = 'rechazada',
           resuelto_en = resolved_at,
           id_perfil_resolutor = p_id_perfil_propietario,
           motivo_rechazo = normalized_reason
     WHERE payment_request.id_solicitud_pago = request_row.id_solicitud_pago
     RETURNING * INTO request_row;

    INSERT INTO public."Notificacion" (
      titulo,
      mensaje,
      tipo,
      icono,
      enlace,
      rol_destino,
      rol_emisor,
      id_perfil_destino,
      id_perfil_emisor,
      leida
    ) VALUES (
      'Pago no confirmado',
      format('El propietario no confirmó el pago de %s. Motivo: %s', coalesce(payment_row.periodo, 'el período actual'), normalized_reason),
      'pago_rechazado',
      'error',
      'tu-alquiler.html#alquiler',
      'TENANT',
      'OWNER',
      contract_row.id_perfil_inquilino,
      contract_row.id_perfil_propietario,
      false
    );
  END IF;

  RETURN QUERY
    SELECT request_row.id_solicitud_pago,
           request_row.estado,
           request_row.resuelto_en,
           payment_row.id_pago,
           payment_row.fecha_pago;
END;
$$;

REVOKE ALL ON FUNCTION public.solicitar_revision_pago(bigint, bigint, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.resolver_revision_pago(bigint, bigint, boolean, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.solicitar_revision_pago(bigint, bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.resolver_revision_pago(bigint, bigint, boolean, text) TO service_role;

COMMIT;
